import React from 'react'
import { type PropsWithChildren } from 'react'
import './globals.css'
import { Raleway } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import data from '@/components/data/data.json'

export const raleway = Raleway({
  subsets: ['latin'],
  weight: ['500']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  const { headerTitle, linksHeader, linksFooter, footerTitle } = data.navigation
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`${raleway.className} ${raleway.className} bg-gray-50`}>
        <main className='container mx-auto px-32'>
          <header className='flex justify-between pt-3'>
            <div className='text-lg'>
              <Link href='/'>{ headerTitle }</Link>
            </div>
            <nav className='flex gap-12 text-lg leading-7'>
              {
                linksHeader.map(link => (
                  <Link key={link.href} href={ link.href }>{ link.label}</Link>
                ))
              }
            </nav>
          </header>
          {children}
          <footer className='flex flex-col items-center'>
            <div className='flex justify-center gap-6'>
              {
                linksFooter.map(link => (
                  <a key={link.href} href={ link.href} target='_blank' rel="noreferrer">
                    <Image src={ `images/${link.icon}`} alt={link.label} width={48} height={48} />
                  </a>
                ))
              }
            </div>
            <small className='text-brand-grayMedium text-base mt-8 mb-20'>{ footerTitle }</small>
          </footer>
        </main>
      </body>
    </html>
  )
}

export default RootLayout
