import React from 'react'
import { type PropsWithChildren } from 'react'
import './globals.css'
import { Raleway } from 'next/font/google'

export const raleway = Raleway({
  subsets: ['latin'],
  weight: ['500']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${raleway.className} ${raleway.className} bg-gray-50`}>{children}</body>
    </html>
  )
}

export default RootLayout
